### ISSUE TITLE
v1.2.0 roadmap

### ISSUE THREAD

**Issue by trigaten** [trigaten/Learn_Prompting#87]
# Content Additions

This release will focus on usability improvements, as well as rounding out content. A ton of new content will be added.

## New Chapters
- [x] Chapter dedicated to beginners @trigaten 
- [x] 🎵 Music prompting (Riffusion) @junosha
- [x] 🖼️ Image prompting (add actual content) @trigaten 
...more
## New Articles
- [x] 🔨 add more IDEs https://github.com/trigaten/Learn_Prompting/pull/100
- [x] 🔓jailbreaks/adversarial #125 https://github.com/trigaten/Learn_Prompting/pull/156 @wahub-ahmed 
- [x] 💥additional topics #93 #91
- [x] More on injection
- [x] 📦 improve products page https://github.com/trigaten/Learn_Prompting/pull/164
...more
# UX improvements
- [x] ✏️improve splash page https://github.com/trigaten/Learn_Prompting/issues/83
...more
# Meta
- [x] More on process of learning to write prompts (intro chapter does this)
